app.name=ResearchPublicationsApp
app.version=1.0.0

db.url=jdbc:mysql://localhost:3306/research_publications_db
db.username=root
db.password=antoniadou
db.driver=com.mysql.cj.jdbc.Driver
db.pool.size=10